# Telttur configuration
# Bounding box in WGS84 (lat/lon)
bbox:
  north: 60.12
  south: 59.8
  east: 10.9
  west: 10.4

min_lake_area_m2: 1000  # exclude lakes smaller than 0.1 ha

map:
  base_map: selectable
