# Telttur configuration
fylke: Akershus

# Output filename
output_filename: map_akershus.html

min_lake_area_m2: 1000  # exclude lakes smaller than 0.1 ha

min_lake_tenting_quality: Fair

lake_display_mode: marker

show_roads: false

# Map rendering options
map:
  interactive_controls:
    enabled: true
    dimension_toggles:
      cabin_density: true
      accessibility: true
      ar5_land_use: true
    min_lake_area: true
    accessibility_thresholds:
      fair: true
      poor: true

